name: ${project.name}
version: ${project.version}
main: ${bukkit.plugin.main}

author: ${bukkit.plugin.authors}

permissions:
  jumppad.allow.fly:
    description: Allow player to fly.
    default: true